### PR TITLE
Fix uninitialized constant DateTime

### LINKED ISSUE #80: uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)
I've been getting this error when using `SafeYAML` without `bundle exec`. On a cursory look, it seems like the cause is a reference to `DateTime` without pulling it in from the Ruby standard library. :cold_sweat:  

Backtrace follows:

```
/Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:22:in `<class:Date>': uninitialized constant SafeYAML::Parse::Date::DateTime (NameError)
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:3:in `<class:Parse>'
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:2:in `<module:SafeYAML>'
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/parse/date.rb:1:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:14:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/lib/kitchen/loader/yaml.rb:27:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/lib/kitchen.rb:42:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/lib/kitchen/cli.rb:21:in `<top (required)>'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /opt/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /Users/s/.gem/ruby/2.2.3/gems/test-kitchen-1.4.2/bin/kitchen:10:in `<top (required)>'
    from /Users/s/.gem/ruby/2.2.3/bin/kitchen:23:in `load'
    from /Users/s/.gem/ruby/2.2.3/bin/kitchen:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by elifoster**
This resolves #80.

### CODE REVIEW

**Comment by Nokel81** [comment]
Can someone please pull this!

**Comment by perlun** [comment]
@dtao Any update on when we can anticipate this to get merged?

**Comment by unnnyong** [comment]
@dtao 

When you release new version with this pull request codes?

**Comment by sean-smith** [comment]
Any update on when this will get released?

**Comment by dtao** [comment]
@unnnyong Thanks for the reminder! I will try to release a new version today.

**Comment by dtao** [comment]
Done: released 1.0.5. https://rubygems.org/gems/safe_yaml

**Comment by sean-smith** [comment]
That was fast! Thanks so much 👍🏻

**Pull request merged**
